import type {Metadata} from "next";
import {Inter} from "next/font/google";
import {ReactNode} from "react";
import Image from "next/image";
import "./globals.css";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: ReactNode; }>) {
  return (
    <html lang="en">
    <body className={`${inter.className} grid grid-rows-1fr-100-1fr h-screen text-white`}>
      <header className="flex items-center justify-between h-14 p-4 text-white border-b border-slate-100/10">
        <div>
          <Image src={'/header-logo.svg'} alt={'Header logo'} width={128} height={64} />
        </div>
      </header>

      <main className="flex flex-col items-center justify-between p-24 h-full">
        {children}
      </main>
    </body>
    </html>
  );
}
